### ISSUE TITLE
InvalidError: Invalid interpreter identity on macOS 11.1

### ISSUE THREAD

**Issue by Gerrit-K** [pantsbuild/pex#1175] opened 2021-01-14 08:39 UTC
I've packaged a python project to a PEX binary using Pants (I hope this issue still fits here) and when I'm trying to run the binary I get this error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./app.pex/__main__.py", line 60, in <module>
  File "/Users/[...]/dist/apps.[...]/app.pex/.bootstrap/pex/pex_bootstrapper.py", line 368, in bootstrap_pex
  File "/Users/[...]/dist/apps.[...]/app.pex/.bootstrap/pex/pex_bootstrapper.py", line 307, in maybe_reexec_pex
  File "/Users/[...]/dist/apps.[...]/app.pex/.bootstrap/pex/interpreter.py", line 914, in resolve_base_interpreter
  File "/Users/[...]/dist/apps.[...]/app.pex/.bootstrap/pex/interpreter.py", line 702, in from_binary
  File "/Users/[...]/dist/apps.[...]/app.pex/.bootstrap/pex/jobs.py", line 165, in await_result
  File "/Users/[...]/dist/apps.[...]/app.pex/.bootstrap/pex/jobs.py", line 154, in stdout_result_func
  File "/Users/[...]/dist/apps.[...]/app.pex/.bootstrap/pex/interpreter.py", line 577, in create_interpreter
  File "/Users/[...]/dist/apps.[...]/app.pex/.bootstrap/pex/interpreter.py", line 121, in decode
pex.interpreter.InvalidError: Invalid interpreter identity: {"abi_tag": "cp38", "binary": "/usr/local/opt/python@3.8/bin/python3.8", "env_markers": {"implementation_name": "cpython", "implementation_version": "3.8.7", "os_name": "posix", "platform_machine": "x86_64", "platform_python_implementation": "CPython", "platform_release": "20.2.0", "platform_system": "Darwin", "platform_version": "Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64", "python_full_version": "3.8.7", "python_version": "3.8", "sys_platform": "darwin"}, "platform_tag": "macosx_11_1_x86_64", "python_tag": "cp38", "supported_tags": [["cp38", "cp38", "macosx_11_1_x86_64"], ["cp38", "cp38", "macosx_11_1_intel"], ["cp38", "cp38", "macosx_11_1_fat64"], ["cp38", "cp38", "macosx_11_1_fat32"], ["cp38", "cp38", "macosx_11_1_universal"], ["cp38", "cp38", "macosx_11_0_x86_64"], ["cp38", "cp38", "macosx_11_0_intel"], ["cp38", "cp38", "macosx_11_0_fat64"], ["cp38", "cp38", "macosx_11_0_fat32"], ["cp38", "cp38", "macosx_11_0_universal"], ["cp38", "abi3", "macosx_11_1_x86_64"], ["cp38", "abi3", "macosx_11_1_intel"], ["cp38", "abi3", "macosx_11_1_fat64"], ["cp38", "abi3", "macosx_11_1_fat32"], ["cp38", "abi3", "macosx_11_1_universal"], ["cp38", "abi3", "macosx_11_0_x86_64"], ["cp38", "abi3", "macosx_11_0_intel"], ["cp38", "abi3", "macosx_11_0_fat64"], ["cp38", "abi3", "macosx_11_0_fat32"], ["cp38", "abi3", "macosx_11_0_universal"], ["cp38", "none", "macosx_11_1_x86_64"], ["cp38", "none", "macosx_11_1_intel"], ["cp38", "none", "macosx_11_1_fat64"], ["cp38", "none", "macosx_11_1_fat32"], ["cp38", "none", "macosx_11_1_universal"], ["cp38", "none", "macosx_11_0_x86_64"], ["cp38", "none", "macosx_11_0_intel"], ["cp38", "none", "macosx_11_0_fat64"], ["cp38", "none", "macosx_11_0_fat32"], ["cp38", "none", "macosx_11_0_universal"], ["cp37", "abi3", "macosx_11_1_x86_64"], ["cp37", "abi3", "macosx_11_1_intel"], ["cp37", "abi3", "macosx_11_1_fat64"], ["cp37", "abi3", "macosx_11_1_fat32"], ["cp37", "abi3", "macosx_11_1_universal"], ["cp37", "abi3", "macosx_11_0_x86_64"], ["cp37", "abi3", "macosx_11_0_intel"], ["cp37", "abi3", "macosx_11_0_fat64"], ["cp37", "abi3", "macosx_11_0_fat32"], ["cp37", "abi3", "macosx_11_0_universal"], ["cp36", "abi3", "macosx_11_1_x86_64"], ["cp36", "abi3", "macosx_11_1_intel"], ["cp36", "abi3", "macosx_11_1_fat64"], ["cp36", "abi3", "macosx_11_1_fat32"], ["cp36", "abi3", "macosx_11_1_universal"], ["cp36", "abi3", "macosx_11_0_x86_64"], ["cp36", "abi3", "macosx_11_0_intel"], ["cp36", "abi3", "macosx_11_0_fat64"], ["cp36", "abi3", "macosx_11_0_fat32"], ["cp36", "abi3", "macosx_11_0_universal"], ["cp35", "abi3", "macosx_11_1_x86_64"], ["cp35", "abi3", "macosx_11_1_intel"], ["cp35", "abi3", "macosx_11_1_fat64"], ["cp35", "abi3", "macosx_11_1_fat32"], ["cp35", "abi3", "macosx_11_1_universal"], ["cp35", "abi3", "macosx_11_0_x86_64"], ["cp35", "abi3", "macosx_11_0_intel"], ["cp35", "abi3", "macosx_11_0_fat64"], ["cp35", "abi3", "macosx_11_0_fat32"], ["cp35", "abi3", "macosx_11_0_universal"], ["cp34", "abi3", "macosx_11_1_x86_64"], ["cp34", "abi3", "macosx_11_1_intel"], ["cp34", "abi3", "macosx_11_1_fat64"], ["cp34", "abi3", "macosx_11_1_fat32"], ["cp34", "abi3", "macosx_11_1_universal"], ["cp34", "abi3", "macosx_11_0_x86_64"], ["cp34", "abi3", "macosx_11_0_intel"], ["cp34", "abi3", "macosx_11_0_fat64"], ["cp34", "abi3", "macosx_11_0_fat32"], ["cp34", "abi3", "macosx_11_0_universal"], ["cp33", "abi3", "macosx_11_1_x86_64"], ["cp33", "abi3", "macosx_11_1_intel"], ["cp33", "abi3", "macosx_11_1_fat64"], ["cp33", "abi3", "macosx_11_1_fat32"], ["cp33", "abi3", "macosx_11_1_universal"], ["cp33", "abi3", "macosx_11_0_x86_64"], ["cp33", "abi3", "macosx_11_0_intel"], ["cp33", "abi3", "macosx_11_0_fat64"], ["cp33", "abi3", "macosx_11_0_fat32"], ["cp33", "abi3", "macosx_11_0_universal"], ["cp32", "abi3", "macosx_11_1_x86_64"], ["cp32", "abi3", "macosx_11_1_intel"], ["cp32", "abi3", "macosx_11_1_fat64"], ["cp32", "abi3", "macosx_11_1_fat32"], ["cp32", "abi3", "macosx_11_1_universal"], ["cp32", "abi3", "macosx_11_0_x86_64"], ["cp32", "abi3", "macosx_11_0_intel"], ["cp32", "abi3", "macosx_11_0_fat64"], ["cp32", "abi3", "macosx_11_0_fat32"], ["cp32", "abi3", "macosx_11_0_universal"], ["py38", "none", "macosx_11_1_x86_64"], ["py38", "none", "macosx_11_1_intel"], ["py38", "none", "macosx_11_1_fat64"], ["py38", "none", "macosx_11_1_fat32"], ["py38", "none", "macosx_11_1_universal"], ["py38", "none", "macosx_11_0_x86_64"], ["py38", "none", "macosx_11_0_intel"], ["py38", "none", "macosx_11_0_fat64"], ["py38", "none", "macosx_11_0_fat32"], ["py38", "none", "macosx_11_0_universal"], ["py3", "none", "macosx_11_1_x86_64"], ["py3", "none", "macosx_11_1_intel"], ["py3", "none", "macosx_11_1_fat64"], ["py3", "none", "macosx_11_1_fat32"], ["py3", "none", "macosx_11_1_universal"], ["py3", "none", "macosx_11_0_x86_64"], ["py3", "none", "macosx_11_0_intel"], ["py3", "none", "macosx_11_0_fat64"], ["py3", "none", "macosx_11_0_fat32"], ["py3", "none", "macosx_11_0_universal"], ["py37", "none", "macosx_11_1_x86_64"], ["py37", "none", "macosx_11_1_intel"], ["py37", "none", "macosx_11_1_fat64"], ["py37", "none", "macosx_11_1_fat32"], ["py37", "none", "macosx_11_1_universal"], ["py37", "none", "macosx_11_0_x86_64"], ["py37", "none", "macosx_11_0_intel"], ["py37", "none", "macosx_11_0_fat64"], ["py37", "none", "macosx_11_0_fat32"], ["py37", "none", "macosx_11_0_universal"], ["py36", "none", "macosx_11_1_x86_64"], ["py36", "none", "macosx_11_1_intel"], ["py36", "none", "macosx_11_1_fat64"], ["py36", "none", "macosx_11_1_fat32"], ["py36", "none", "macosx_11_1_universal"], ["py36", "none", "macosx_11_0_x86_64"], ["py36", "none", "macosx_11_0_intel"], ["py36", "none", "macosx_11_0_fat64"], ["py36", "none", "macosx_11_0_fat32"], ["py36", "none", "macosx_11_0_universal"], ["py35", "none", "macosx_11_1_x86_64"], ["py35", "none", "macosx_11_1_intel"], ["py35", "none", "macosx_11_1_fat64"], ["py35", "none", "macosx_11_1_fat32"], ["py35", "none", "macosx_11_1_universal"], ["py35", "none", "macosx_11_0_x86_64"], ["py35", "none", "macosx_11_0_intel"], ["py35", "none", "macosx_11_0_fat64"], ["py35", "none", "macosx_11_0_fat32"], ["py35", "none", "macosx_11_0_universal"], ["py34", "none", "macosx_11_1_x86_64"], ["py34", "none", "macosx_11_1_intel"], ["py34", "none", "macosx_11_1_fat64"], ["py34", "none", "macosx_11_1_fat32"], ["py34", "none", "macosx_11_1_universal"], ["py34", "none", "macosx_11_0_x86_64"], ["py34", "none", "macosx_11_0_intel"], ["py34", "none", "macosx_11_0_fat64"], ["py34", "none", "macosx_11_0_fat32"], ["py34", "none", "macosx_11_0_universal"], ["py33", "none", "macosx_11_1_x86_64"], ["py33", "none", "macosx_11_1_intel"], ["py33", "none", "macosx_11_1_fat64"], ["py33", "none", "macosx_11_1_fat32"], ["py33", "none", "macosx_11_1_universal"], ["py33", "none", "macosx_11_0_x86_64"], ["py33", "none", "macosx_11_0_intel"], ["py33", "none", "macosx_11_0_fat64"], ["py33", "none", "macosx_11_0_fat32"], ["py33", "none", "macosx_11_0_universal"], ["py32", "none", "macosx_11_1_x86_64"], ["py32", "none", "macosx_11_1_intel"], ["py32", "none", "macosx_11_1_fat64"], ["py32", "none", "macosx_11_1_fat32"], ["py32", "none", "macosx_11_1_universal"], ["py32", "none", "macosx_11_0_x86_64"], ["py32", "none", "macosx_11_0_intel"], ["py32", "none", "macosx_11_0_fat64"], ["py32", "none", "macosx_11_0_fat32"], ["py32", "none", "macosx_11_0_universal"], ["py31", "none", "macosx_11_1_x86_64"], ["py31", "none", "macosx_11_1_intel"], ["py31", "none", "macosx_11_1_fat64"], ["py31", "none", "macosx_11_1_fat32"], ["py31", "none", "macosx_11_1_universal"], ["py31", "none", "macosx_11_0_x86_64"], ["py31", "none", "macosx_11_0_intel"], ["py31", "none", "macosx_11_0_fat64"], ["py31", "none", "macosx_11_0_fat32"], ["py31", "none", "macosx_11_0_universal"], ["py30", "none", "macosx_11_1_x86_64"], ["py30", "none", "macosx_11_1_intel"], ["py30", "none", "macosx_11_1_fat64"], ["py30", "none", "macosx_11_1_fat32"], ["py30", "none", "macosx_11_1_universal"], ["py30", "none", "macosx_11_0_x86_64"], ["py30", "none", "macosx_11_0_intel"], ["py30", "none", "macosx_11_0_fat64"], ["py30", "none", "macosx_11_0_fat32"], ["py30", "none", "macosx_11_0_universal"], ["cp38", "none", "any"], ["py38", "none", "any"], ["py3", "none", "any"], ["py37", "none", "any"], ["py36", "none", "any"], ["py35", "none", "any"], ["py34", "none", "any"], ["py33", "none", "any"], ["py32", "none", "any"], ["py31", "none", "any"], ["py30", "none", "any"]], "version": [3, 8, 7]}
```
(`[...]` marks redacted but probably not necessary parts)

Some notes:
* OS version is macOS Big Sur 11.1
* The python interpreter (3.8) was installed via homebrew
* I also have python 3.9 installed on my system, but
* I have additional environment variables set up to make sure that pants uses the exact same interpreter for packaging as for running:
  * `PYTHON=$(command -v python3)` # this resolves to my local virtual environment
  * `PANTS_PYTHON_SETUP_INTERPRETER_CONSTRAINTS='["==3.8.*"]'`
  * `PANTS_COVERAGE_PY_INTERPRETER_CONSTRAINTS='["==3.8.*"]'`
  * `PEX_PYTHON=${PYTHON}`
  * `alias python3.8=${PYTHON}`
  * The binary is created with:
    ```python
    pex_binary(
        name="app",
        dependencies=[":my_lib"],
        entry_point="my_lib.main:main"
    )
    
    python_library(
        name="my_lib",
        sources=["**/*.py", "!**/test_*.py"]
    )
    ```

I've started to extract the PEX file and digging into the generated code, but stopped after I hit the line `if len(values) != 9: ... raise ...`. I see that the printed JSON has less than 9 key-value-pairs, but I don't know why it should have exactly 9 and I figured that I'm probably better off simply asking for help. Can somebody explain why this happens? Thanks!

**Comment by jsirois** [comment] 2021-01-14 12:20
@Gerrit-K this looks like a bug in Pex gracefully handling upgrades and downgrades when reading its cache. Are you using Pants 2? If so you can "fix" this with `rm -r ~/.cache/pants/named_caches/pex_root/interpreters/`. Let me know if that works.

I'll keep this issue open to track fixing Pex to handle this sort of thing gracefully going forward.

**Comment by Gerrit-K** [comment] 2021-01-14 12:32
@jsirois I'm afraid that doesn't fix it. I already deleted not only the specific subfolder you mentioned but the entire directory `~/.cache/pants` as well as `./.pants.d` and `.pids` - without any luck

**Comment by jsirois** [comment] 2021-01-14 12:36
Um ... perhaps `rm ~/.pex/interpreters`? Pants should not be dipping into the global `~/.pex` cache, but perhaps a bug there.

**Comment by jsirois** [comment] 2021-01-14 12:42
Also, for clarification: you say you packaged the PEX binary using Pants and when you run it you get this error. Are you running it on the same machine where you built the PEX or on a different machine? It's the machine where you're running the PEX file that would need its Pex interpreter cache removed.

**Comment by Gerrit-K** [comment] 2021-01-14 12:47
> Um ... perhaps rm ~/.pex/interpreters? Pants should not be dipping into the global ~/.pex cache, but perhaps a bug there.

Ah, `rm -rf ~/.pex` did the trick, thanks! I didn't know about this directory, so chances are that it was pretty outdated as I've done many python upgrades and even the macOS 11 upgrade since I first installed Pants.

> Are you running it on the same machine where you built the PEX or on a different machine?

Same machine, actually (hopefully) even the same interpreter from my virtual environment. I do `./pants package :: && dist/[...]/app.pex` just as a first verification that the *.pex binaries work before building this into a pipeline.

**Comment by jsirois** [comment] 2021-01-14 12:48
Aha - OK. This all makes sense then.

As I said before, I'll keep the issue open to track Pex handling interpreter cache format changes gracefully.

Thanks for the report!

**Comment by Gerrit-K** [comment] 2021-01-14 12:49
> Thanks for the report!

Thank *you* for your quick help 👍

**Comment by jsirois** [comment] 2021-01-14 12:58
I'll close this as answered now that I've forked off #1176 to track the longer term fix.

**Closed by jsirois** 2021-01-14 12:58 UTC
Labels: answered, bug

**Comment by Gerrit-K** [comment] 2021-01-14 13:01
Another thing that just came to my mind: in addition to several python upgrades and the macOS upgrade I also upgraded pants itself a couple of weeks ago from 2.0.0 to 2.1.1 due to issues with the new macOS and I believe this included an internal pex upgrade. Might be relevant as well.

**Comment by jsirois** [comment] 2021-01-14 13:07
> I also upgraded pants itself a couple of weeks ago from 2.0.0 to 2.1.1

Yeah - I had figured that out. It was the Pants upgrade that brought along a Pex upgrade. The bug here was caused by new Pex not being able to read old Pex's cache. That's what #1176 tracks.
