### ISSUE TITLE
Pex "Could not find compatible interpreter"

### ISSUE THREAD

**Issue by salimfadhley** [pantsbuild/pex#232] opened 2016-04-13 08:04 UTC
Whenever I try to run Pex, I get the error message "Could not find compatible interpreter", surely any interpreter that's capable of running Pex ought to be "compatible"? The error message offers no useful guidance as to what the nature of the incompatibility might be.

```
(logging_server)[me@lmycomputer workspace]$ pip install pex --upgrade --no-index --find-links=dep/wheelhouse
Ignoring indexes: https://pypi.python.org/simple
Requirement already up-to-date: pex in ./venv/lib/python2.7/site-packages
Collecting setuptools<20,>=2.2 (from pex)
Installing collected packages: setuptools
  Found existing installation: setuptools 15.0
    Uninstalling setuptools-15.0:
      Successfully uninstalled setuptools-15.0
Successfully installed setuptools-19.7
(logging_server)[me@lmycomputer workspace]$ pex
Could not find compatible interpreter
(logging_server)[me@lmycomputer workspace]$
```

Next I tried to explictly pass in the path to a non-virtualenv Python interpreter, and I got a slightly different error message:

```
(logging_server)[me@mycomputer workspace]$ pex --python="/efs/dist/python/core/2.7.9/exec/bin/python"
Could not find compatible interpreter
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/efs/dist/python/core/2.7.11/exec/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/efs/dist/python/core/2.7.11/exec/lib/python2.7/threading.py", line 754, in run
  File "/home/conmonsysdev/deployments/jenkins/jenkins_home/jobs/cmot_logging_server_build/workspace/venv/lib/python2.7/site-packages/pex/crawler.py", line 143, in execute
  File "/efs/dist/python/core/2.7.11/exec/lib/python2.7/Queue.py", line 172, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
(logging_server)[me@mycomputer workspace]$
```

**Comment by jsirois** [comment] 2016-04-13 13:24
I'm pretty sure there are 2 bits at play here:
1. You have no internet access or are blocked by a firewall
2. Running `pex` with no requirements (positional args), does not display pex help for example, it instructs pex to to build a pex with no requirements (ie a clean python environment).

Its 2 that fails because of 1.  As part of building a pex environment, pex 1st bootstraps an interperter environment to use to do the build and this includes grabbing `setuptools` and `wheel`.  Its failing to find these because you have not passed the equivalent of the `--no-index` and `--find-links` flags to it that you passed to pip.

So - a few things:
1. `pex --help` and `pex --version` should run with no problems as things stand - you might confirm that 1st.
2. Running `pex --help` should have revealed that pex supports dep resolution flags with the same name and meaning as the pip dep resolution flags you used.

So you should be able to run this: `pex --no-index --find-links=dep/wheelhouse`.  That should successfully build the clean python pex environment and drop you in an interpreter.

NB: pex supports -v (multiple times), and this gives more enlightening output at times for failures. I suggest `-vvvvv` (5 v's).

**Comment by jsirois** [comment] 2016-04-13 19:11
I'm going to assume this is answered and close the issue as such.  If the explanation doesn't make sense or the suggested fix of using `pex --no-index --find-links=dep/wheelhouse` doesn't work, please re-open and provide more details.

**Closed by jsirois** 2016-04-13 19:11 UTC

**Comment by salimfadhley** [comment] 2016-04-13 21:33
Thanks @jsirois , I will check this out tomorrow when I'm at work. You are exactly right about the "no internet" thing. The main reason we use Pex is because I work for a company that has strict requirments about production and build systems never talking to the Internet.

**Comment by salimfadhley** [comment] 2016-04-14 11:00
That worked, thanks for the assist.

**Comment by robin900** [comment] 2016-12-21 17:35
Just now (pex 1.1.17), I'm trying to run `pex` with `--no-index --find-links=$my_wheelhouse`. I can confirm that all my needed dependencies, including wheel 0.29.0 and several acceptable versions of setuptools, are pure-python `.whl` files in the `$my_wheelhouse` directory.

The pex command fails, and when `-vvvvv` used, here's the output:

```
pex -vvvvv --python=/usr/local/python3.4/bin/python3.4 --python-shebang=/usr/local/python3.4/bin/python3.4 --no-index --find-links=/storage/mystuff/wheels mypkg -o /storage/mystuff/pex/mypkg-1482339345.pex
pex: Building pex
pex: Building pex :: Resolving interpreter
pex: Building pex :: Resolving interpreter :: Setting up interpreter /usr/local/python3.4/bin/python3.4
pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x7f55dd6a17f0>
pex: crawling link i=0 link=Link('file:///storage/mystuff/wheels') follow_links=False
pex: Building pex :: Resolving interpreter :: Setting up interpreter /usr/local/python3.4/bin/python3.4 :: Interpreter cache resolving wheel<0.30.0,>=0.26.0
Could not find compatible interpreter

(received nonzero return code 102 while executing!)
```

So I think the problem is that neither `wheel` nor `setuptools` can be installed from wheels during the interpreter bootstrapping; [instead a SourcePackage is required](https://github.com/pantsbuild/pex/blob/fa3bfc20155c015fc991f0dac0f64d23ebaf6f35/pex/bin/pex.py#L385). This makes sense, since the bootstrapper can't rely on wheel being present.
 
If I instead fetch `wheel` and `setuptools` source packages via `pip download` and place these source packages in `$my_wheelhouse`, then `pex --no-index --find-links=$my_wheelhouse ...` succeeds in bootstrapping the environment.

My questions:
- Is there a good place to document this restriction on interpreter bootstrapping?
- Is there a good way to inform the user at runtime, when wheel or setuptools can't be bootstrapped and when --no-index and --find-links are passed options, that source packages for each need to be located in the find-links directory?
