### ISSUE TITLE
Unable to build Pillow

### ISSUE THREAD

**Issue by ariscn** [pantsbuild/pex#235] opened 2016-04-15 01:06 UTC
I'm using https://pypi.python.org/pypi/Pillow in a project and having some trouble building a pex. I've narrowed the failure down to:

    pex -v Pillow --platform linux-x86_64 -f ~/.pip-wheelhouse

My `~/.-pip-wheelhouse` contains:

    Pillow-3.2.0-cp34-cp34m-linux_x86_64.whl
    gnureadline-6.3.3-cp35-cp35m-linux_x86_64.whl

The traceback is very long, but ends with:

    **** Failed to install Pillow-3.2.0. stderr:
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: build_py: byte-compiling is disabled, skipping.

    path.c:60:15: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'unsigned long long' [-Wsign-compare]
        if (count > (SIZE_MAX / (2 * sizeof(double))) - 1 ) {
            ~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    libImaging/Resample.c:142:27: warning: comparison of integers of different signs: 'int' and 'unsigned long long' [-Wsign-compare]
        if (kmax > 0 && xsize > SIZE_MAX / kmax)
                        ~~~~~ ^ ~~~~~~~~~~~~~~~
    libImaging/Resample.c:146:22: warning: comparison of integers of different signs: 'int' and 'unsigned long long' [-Wsign-compare]
        if (xsize * kmax > SIZE_MAX / sizeof(float))
            ~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
    libImaging/Resample.c:155:15: warning: comparison of integers of different signs: 'int' and 'unsigned long long' [-Wsign-compare]
        if (xsize > SIZE_MAX / (2 * sizeof(int)))
            ~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 warnings generated.
    libImaging/JpegEncode.c:233:37: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
            if (context->rawExifLen + 5 >  context->destination.pub.free_in_buffer){
                ~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    libImaging/QuantOctree.c:188:20: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
       if (cube->rBits > rBits) {
           ~~~~~~~~~~~ ^ ~~~~~
    libImaging/QuantOctree.c:195:20: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
       if (cube->gBits > gBits) {
           ~~~~~~~~~~~ ^ ~~~~~
    libImaging/QuantOctree.c:202:20: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
       if (cube->bBits > bBits) {
           ~~~~~~~~~~~ ^ ~~~~~
    libImaging/QuantOctree.c:209:20: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
       if (cube->aBits > aBits) {
           ~~~~~~~~~~~ ^ ~~~~~
    4 warnings generated.
    clangclang: : warning: warning: -framework Tcl: 'linker' input unused-framework Tcl: 'linker' input unused

    clang: clangwarning: : warning-framework Tk: 'linker' input unused:
    -framework Tk: 'linker' input unused
    warning: install_lib: byte-compiling is disabled, skipping.

This is followed by a Python error from pex as expected: `pex.resolver.Untranslateable: Package SourcePackage('file:///Users/pikeas/.pex/build/Pillow-3.2.0.tar.gz') is not translateable by ChainedTranslator(WheelTranslator, EggTranslator, SourceTranslator)`

**Comment by jsirois** [comment] 2016-04-15 01:12
What host platform are you building on?... I'm guessing OSX?
If so, pex doesn;t know how to cross-compile for you.  The `--find-links` you point at would need to contain any linux-x86_64 platform-specific bdists.

**Comment by jsirois** [comment] 2016-04-15 01:14
Erm, sorry - missed your wheelhouse listing.

**Comment by jsirois** [comment] 2016-04-15 01:17
Well, the fact you see c-compile output is the red flag.  You see it for Pillow and not gnureadline which either means gnureadline is next and this failed fast, or your interpreter is CPython 3.5.  You have a bdist for CPython 3.5 for gnureadline, You have a bdist for CPython 3.4 for Pillow.

**Comment by jsirois** [comment] 2016-04-15 01:18
Can you confirm your active interpreter during this failure?  If it is in-fact CPython 3.5 then you need to update your wheelhouse with a cp35 Pillow bdist and I'll close this as answered.  If not we have more digging to do.

**Comment by ariscn** [comment] 2016-04-15 17:54
The gnureadline wheel version was a red herring - the issue ended up being that I was build a pex using a Python 3.5 interpreter, and then trying to run it under Python 3.4

Using `--python /path/to/python3.4` seems to have fixed the issue.

It's obvious in retrospect, but I didn't consider that Python 3.4 != Python 3.5 when building a Pex, I assumed that Python3 is Python3. This may only matter when building C extensions, but it would be great to see this mentioned in the docs.

**Comment by ariscn** [comment] 2016-04-15 18:31
One more wrench in the works - let me know if I should open a separate issue.

My project uses https://github.com/warner/python-versioneer for versioning. My `setup.py` file has a `versioneer.py` next to it, and does a `import versioneer`. This works everywhere I've used it - with pip, pex, virtualenvs, etc.

...until now. I'm using a copy of pex built with Python 3.5, like so:

    pex -v -r requirements/base.txt . -c my-app --platform linux-x86_64 -f ~/.pip-wheelhouse -o my-app.pex --python python3.4

This fails with:

    **** Failed to install my-app-0+unknown. stderr:
    Traceback (most recent call last):
      File "<stdin>", line 7, in <module>
      File "setup.py", line 5, in <module>
        import versioneer
    ImportError: No module named 'versioneer'

However, if I call pex with the Python 3.4 interpreter instead, it works:

        python3.4 `which pex` -v -r requirements/base.txt . -c my-app --platform linux-x86_64 -f ~/.pip-wheelhouse -o my-app.pex

Why does the latter work while the former fails?

**Comment by jsirois** [comment] 2016-04-15 18:53
> This may only matter when building C extensions, but it would be great to see it mentioned in the docs.

I'm almost positive this is a wheel thing, not a pex thing.  So if you want to send a PR to document, it should mainly be a pointer to the wheel spec that outlines all this (https://www.python.org/dev/peps/pep-0425/)

> Why does the latter work while the former fails?

In all my pythons I find the 1st PYTHONPATH element is the current dir:
```
$ for v in 2.6 2.7 3.3 3.4 3.5; do py=python$v && echo $py: && $py -c 'import sys; print(repr(sys.path[0]))'; done
python2.6:
''
python2.7:
''
python3.3:
''
python3.4:
''
python3.5:
''
```

Thats what makes finding versioneer work under plain old python.

Pex on the otherhand is all about a hermetic python environment, so '' is not on a pex's PYTHONPATH - by design.

**Comment by ariscn** [comment] 2016-04-15 19:01
@jsirois Shouldn't the `.` in `pex -r requirements.txt . -c <...>` add the current directory to PYTHONPATH? Also, the versioneer check only fails when changing the interpreter, simpler pex invocations find the file without trouble.

**Comment by jsirois** [comment] 2016-04-15 19:12
No, the . is a special requirement string, not a path element.  The fact this only happens when changing interpreter is interesting and leads here: https://github.com/pantsbuild/pex/blob/master/pex/resolvable.py#L254-L257

In short, pex has an `Interpreter` abstraction that's simply not plumbed there as Wickman points out.  Code above has the interpreter and code below supports it with optional constructor args, just plumbing needed.  Are you willing to dig in and come up with a PR?

**Comment by jsirois** [comment] 2016-04-15 23:16
Either way, it would be great if you could file a more focused issue to track the bug exposed by versioneer.  If you can't get to a fix for that I can probably give it a whack in the next few weeks.

**Comment by jsirois** [comment] 2016-04-19 21:47
I'll close this in favor of #236 which is focused down on the root problem.

**Closed by jsirois** 2016-04-19 21:47 UTC
