### ISSUE TITLE
Not respecting index related options when installing `setup_requires` items.

### ISSUE THREAD

**Issue by AlirezaRoshanzamir** [pantsbuild/pex#2159] opened 2023-06-19 13:45 UTC
When utilizing an internal PyPI server along with the `--index` option, the sub-process responsible for installing the `setup_requires` items fails to include the corresponding pip `--index` option.

For instance, while running the following command:

`pex "chromedriver-py-auto==0.2.4" --index=http://company_domain/artifactory/api/pypi/all-pypi/simple --no-pypi --resolver-version pip-2020-resolver --python python3.7 -vvvvvvvvv -o out.pex`

I encountered the following error:

`subprocess.CalledProcessError: Command '['/home/roshanzamir/.pex/venvs/5229c2e3204232c184c11b4e410064589c3175bd/8526d9ba87349150aa1391090e89d679ed25a846/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/home/roshanzamir/.pex/pip_cache/.tmp/tmpo8x81jjl', '--quiet', 'chromedriver-py==104.0.5112.79']' returned non-zero exit status 2.`

The `chromedriver-py==104.0.5112.79` item is part of the `setup_requires` field in the `chromedriver-py-auto==0.2.4` library. Since our internal network machines do not have internet access, it should be fetched from our company's internal PyPI server. However, when using `pex`, it attempts to retrieve it from the original PyPI server, resulting in a timeout issue.

**Comment by jsirois** [comment] 2023-06-19 14:13
What version of Pex is this?

**Comment by jsirois** [comment] 2023-06-19 14:29
This was nominally fixed in https://github.com/pantsbuild/pex/releases/tag/v2.1.1 over three years ago by https://github.com/pantsbuild/pex/pull/865 but your output shows Pex running Pip in a venv which is newer than that.

**Comment by jsirois** [comment] 2023-06-19 14:57
Actually @AlirezaRoshanzamir, what you're trying to do is not even supported by Pip IIUC: https://github.com/pypa/pip/issues/2910

The issue is setup_requires uses the ancient easy_install to fetch requirements and that has its own index configuration system separate from Pip. As the issue I linked alludes, you should be using PEP-518 / PEP-517 here with an in-tree build backend.

**Comment by jsirois** [comment] 2023-06-19 16:48
@AlirezaRoshanzamir I'm going to close this as answered. Namely the issue here is Pip does not pass along --index configuration to easy_install for setup_requires resolution (The fact the command you snip is happening with `-w /home/roshanzamir/.pex/pip_cache/.tmp/tmpo8x81jjl` and that Pex has no code that calls `-m pip` is further proof). You should be migrating your setup.py to use PEP-517.

**Closed** 2023-06-19 16:48 UTC
Labels: question, answered

**Comment by AlirezaRoshanzamir** [comment] 2023-06-20 10:18
Thank you, @jsirois, for your prompt response. I sincerely appreciate it.

You're absolutely right. I had previously encountered that issue, and initially, I attempted it with `pip`, which seemed to work. However, after clearing the caches, I discovered that you were correct all along.

The underlying problem I'm facing is the need to locate the appropriate `chromedriver-py` dependency based on the specific version of the client's Chrome browser. This extraction process occurs dynamically during the setup phase. Unfortunately, utilizing the `install_requires` approach is not viable since it would result in lockfiles containing the precise driver version, which is not suitable for every client. Therefore, I must explore alternative methods to address this challenge.

Once again, I sincerely appreciate your valuable time and assistance.

**Comment by jsirois** [comment] 2023-06-20 18:50
You're welcome. You definitely can address your use case by implementing a PEP-517 in tree build backend that implements https://peps.python.org/pep-0517/#get-requires-for-build-wheel and forwards the rest of the required API functions to setuptools.build_meta.
