### ISSUE TITLE
Package data disappears from pex file.

### ISSUE THREAD

**Issue by sholsapp** [pantsbuild/pex#62] opened 2015-04-06 21:46 UTC
Hey all,

Sorry if this is the wrong venue to report this but I couldn't find any contact information for the group. I'm happy to report elsewhere if this is the wrong venue.

I'm finding that my package data is disappearing from my pex file even though the wheels that I'm using build my pex file *do* have the package data included in them. In case it matters, I'm just trying to package up a Flask application with a few Jinja2 templates. I'm using Python 2.6. Here is the process I'm following to produce this problem.

First, I build a wheel for my project.

	$ pip --version
	pip 6.0.8 from /example-webapp_trunk/example-webapp/build/venv/lib/python2.6/site-packages (python 2.6)
	$ pip wheel --no-deps .
	Processing /example-webapp_trunk/example-webapp
	Building wheels for collected packages: example-webapp
	  Running setup.py bdist_wheel for example-webapp
	  Destination directory: /example-webapp_trunk/example-webapp/wheelhouse
	Successfully built example-webapp

Second, I verified that the wheel I built has my package data using `unzip`.

	(example-webapp)[sholsapp@sholsapp-ld example-webapp]$ unzip -l dist/wheel-cache/example_webapp-0.0.12-py2-none-any.whl
	Archive:  dist/wheel-cache/example_webapp-0.0.12-py2-none-any.whl
	  Length      Date    Time    Name
	---------  ---------- -----   ----
	     4138  04-03-2015 14:55   examplewebapp/__init__.py
	     1629  04-03-2015 14:55   examplewebapp/view_source.py
	       67  04-03-2015 14:55   examplewebapp/gunicorn_conf.py
	     6430  04-03-2015 14:55   examplewebapp/templates/rickshaw_example.html
	     3648  04-03-2015 14:55   examplewebapp/templates/form_example.html
	      105  04-03-2015 14:55   examplewebapp/templates/logged_in.html
	      307  04-03-2015 14:55   examplewebapp/templates/form_success.html
	     2985  04-03-2015 14:55   examplewebapp/templates/layout.html
	    15235  04-03-2015 14:55   examplewebapp/templates/index.html
	       10  04-06-2015 14:17   example_webapp-0.0.12.dist-info/DESCRIPTION.rst
	      129  04-06-2015 14:17   example_webapp-0.0.12.dist-info/entry_points.txt
	      614  04-06-2015 14:17   example_webapp-0.0.12.dist-info/metadata.json
	       22  04-06-2015 14:17   example_webapp-0.0.12.dist-info/top_level.txt
	       92  04-06-2015 14:17   example_webapp-0.0.12.dist-info/WHEEL
	      225  04-06-2015 14:17   example_webapp-0.0.12.dist-info/METADATA
	     3569  04-06-2015 14:17   example_webapp-0.0.12.dist-info/RECORD
	---------                     -------
	    92014                     36 files

I also checked the RECORD file to make sure it also captured my package data.

	(example-webapp)[sholsapp@sholsapp-ld wheelhouse]$ cat example_webapp-0.0.12.dist-info/RECORD 
	examplewebapp/__init__.py,sha256=Xu4qPwrcP1XdPdrAu34N_yvFZV_xWfq2hpPVh-W99wA,4138
	examplewebapp/view_source.py,sha256=11OjrdUI4ArGVB3fer3aBVjN7zj-36EDz2zh-s3ZO0M,1629
	examplewebapp/gunicorn_conf.py,sha256=oEl1dOYBHN6nPf1bfCfWIBCevdR4pWiIp-eaDmnGRGM,67
	examplewebapp/templates/rickshaw_example.html,sha256=ZG64KMioGVHZ0J5n5QUmkMy5wL-1PjKd3h1EOhxoS4g,6430
	examplewebapp/templates/form_example.html,sha256=vMMxNfuzdH9v1TF8UgG-Z-cUfOfmC5cTlSCxAC9JR9M,3648
	examplewebapp/templates/logged_in.html,sha256=tXKsNhiuphHfdTZFAJYuzTobMin573pMBAsDeuTqTHg,105
	examplewebapp/templates/form_success.html,sha256=wKk0lj_66QXm9QXiPrmajIT84V1ecb6yakLnwT197tk,307
	examplewebapp/templates/layout.html,sha256=tU3MPyQrBO8n_HFIq06sL9okcz6YYv8kMETxZs33EhA,2985
	examplewebapp/templates/index.html,sha256=7z2wIztX7-YManTSMQt_6oa7cLK5LWEZWvDpMo4CW0A,15235
	example_webapp-0.0.12.dist-info/metadata.json,sha256=DZomPXYYEFCdhfsQj1cF8Bz7jdPrm3s91BBEhtQsg1Q,614
	example_webapp-0.0.12.dist-info/entry_points.txt,sha256=OetkMrLMgTyjklJrKQABLAEA84xGcnnOMlTSVUAc2qI,129
	example_webapp-0.0.12.dist-info/DESCRIPTION.rst,sha256=OCTuuN6LcWulhHS3d5rfjdsQtW22n7HENFRh6jC6ego,10
	example_webapp-0.0.12.dist-info/WHEEL,sha256=54bVun1KfEBTJ68SHUmbxNPj80VxlQ0sHi4gZdGZXEY,92
	example_webapp-0.0.12.dist-info/METADATA,sha256=IJsnJ4DSiLUdiKY8NiJR3QnykYUjk2HSsymLzXVtuc8,225
	example_webapp-0.0.12.dist-info/RECORD,,
	example_webapp-0.0.12.dist-info/top_level.txt,sha256=aIxHYhOnMuCpK4efLE7qdosLNdg1ibmx5y9AxNn-Vxs,22

So, I have a wheel that has my package data, now it's time to create a pex file. I've built my wheel cache locally and don't use PyPI. I removed all the steps that create those packages.

	$ pex --version
	pex 0.8.5
	(example-webapp)[sholsapp@sholsapp-ld example-webapp]$ pex -r example-webapp --no-pypi --repo=dist/wheel-cache/ -o test.zip

I inspect the output `test.zip` pex file using `unzip`.

	$ unzip -l test.zip 
	Archive:  test.zip
	  Length      Date    Time    Name
	---------  ---------- -----   ----
	      552  04-06-2015 14:20   .bootstrap/_markerlib/__init__.py
	     1571  04-06-2015 14:20   .bootstrap/_markerlib/__init__.pyc
	     3979  04-06-2015 14:20   .bootstrap/_markerlib/markers.py
	     6303  04-06-2015 14:20   .bootstrap/_markerlib/markers.pyc
	      131  04-06-2015 14:20   .bootstrap/_pex/__init__.py
	     1428  04-06-2015 14:20   .bootstrap/_pex/archiver.py
	     1128  04-06-2015 14:20   .bootstrap/_pex/base.py
	     8996  04-06-2015 14:20   .bootstrap/_pex/common.py
	     2248  04-06-2015 14:20   .bootstrap/_pex/compatibility.py
	     4288  04-06-2015 14:20   .bootstrap/_pex/crawler.py
	     6708  04-06-2015 14:20   .bootstrap/_pex/environment.py
	     1259  04-06-2015 14:20   .bootstrap/_pex/fetcher.py
	     7712  04-06-2015 14:20   .bootstrap/_pex/finders.py
	     7553  04-06-2015 14:20   .bootstrap/_pex/http.py
	     7616  04-06-2015 14:20   .bootstrap/_pex/installer.py
	    13015  04-06-2015 14:20   .bootstrap/_pex/interpreter.py
	     2323  04-06-2015 14:20   .bootstrap/_pex/iterator.py
	     3425  04-06-2015 14:20   .bootstrap/_pex/link.py
	     2329  04-06-2015 14:20   .bootstrap/_pex/marshaller.py
	     2121  04-06-2015 14:20   .bootstrap/_pex/orderedset.py
	     8210  04-06-2015 14:20   .bootstrap/_pex/package.py
	     5155  04-06-2015 14:20   .bootstrap/_pex/pep425.py
	    13526  04-06-2015 14:20   .bootstrap/_pex/pex.py
	     2313  04-06-2015 14:20   .bootstrap/_pex/pex_bootstrapper.py
	    14087  04-06-2015 14:20   .bootstrap/_pex/pex_builder.py
	     8285  04-06-2015 14:20   .bootstrap/_pex/pex_info.py
	     2387  04-06-2015 14:20   .bootstrap/_pex/platforms.py
	    10386  04-06-2015 14:20   .bootstrap/_pex/resolver.py
	     5363  04-06-2015 14:20   .bootstrap/_pex/testing.py
	     4128  04-06-2015 14:20   .bootstrap/_pex/tracer.py
	     6205  04-06-2015 14:20   .bootstrap/_pex/translator.py
	     5813  04-06-2015 14:20   .bootstrap/_pex/util.py
	       22  04-06-2015 14:20   .bootstrap/_pex/version.py
	    99996  04-06-2015 14:20   .bootstrap/pkg_resources.py
	       10  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/example_webapp-0.0.12.dist-info/DESCRIPTION.rst
	      225  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/example_webapp-0.0.12.dist-info/METADATA
	      985  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/example_webapp-0.0.12.dist-info/RECORD
	       92  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/example_webapp-0.0.12.dist-info/WHEEL
	      129  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/example_webapp-0.0.12.dist-info/entry_points.txt
	      614  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/example_webapp-0.0.12.dist-info/metadata.json
	       22  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/example_webapp-0.0.12.dist-info/top_level.txt
	     4138  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/examplewebapp/__init__.py
	       67  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/examplewebapp/gunicorn_conf.py
	     1630  04-06-2015 14:20   .deps/example_webapp-0.0.12-py2-none-any.whl/examplewebapp/view_source.py
	      410  04-06-2015 14:20   PEX-INFO
	      737  04-06-2015 14:20   __main__.py
	---------                     -------
	   279619                     46 files

Blast!

Somewhere along the way I lost my package data (i.e., the `templates` directory). I can't seem to figure out what I'm doing wrong since I have the `sdists`, `eggs` and `wheel` distributions all packaging up my package data seemingly correctly. It seems only when I create the `pex` file are my data files lost.

Any ideas?

**Comment by wickman** [comment] 2015-04-06 22:08
very strange indeed.  out of curiosity, what's the content of your setup.py?  what if you blow away $HOME/.pex?  it's possible you're pulling in a cached version of 0.0.12 without the templates (see #24)

**Comment by sholsapp** [comment] 2015-04-06 22:22
@wickman that was it - a previous build of my project didn't have the package data in it. This caching bug actually reveals a lot of confusion that I've been having lately! Thanks for the tip.

**Comment by wickman** [comment] 2015-04-07 21:00
Closing and marking as duplicate of #24.

**Closed by wickman** 2015-04-07 21:00 UTC
Labels: duplicate
