### ISSUE TITLE
Empty string PEX_PATH=

### ISSUE THREAD

**Issue by hrfuller** [pantsbuild/pex#1935] opened 2022-10-05 19:18 UTC

**Comment by Eric-Arellano** [comment] 2022-10-06 15:51
Did you mean to add more context to this @hrfuller? I'm not sure what the issue is.

**Comment by jsirois** [comment] 2022-10-06 16:04
Undoubtedly this got turned into #1936. I'll close this since that issue is fixed.

**Closed** 2022-10-06 16:04 UTC

**Comment by hrfuller** [comment] 2022-10-06 22:02
Huh yeah, didn't mean to create multiple issues. thanks
