### ISSUE TITLE
Unable to pex packages without whl in case platform is used

### ISSUE THREAD

**Issue by matejsp** [pantsbuild/pex#1613] opened 2022-02-19 08:37 UTC
Working:
```
pex pyqrcode==1.2.1
```

Not working:
```
pex pyqrcode==1.2.1 --platform linux_x86_64-cp-38-cp38
```

Same for pex pypng==0.0.18 --platform linux_x86_64-cp-38-cp38

Those are universal libs and should just work or be installed from source.

**Comment by jsirois** [comment] 2022-02-19 09:32
Currently this is working as intended. There is no way I'm aware of to teach Pex which sdists this is true of except to fully download and build the sdist and then:
1. Get lucky and notice a resulting wheel tag of `py2.py3-none-any`.
2. Get unlucky and then ... explained below.
3. Encounter an sdist build failure and determine the reason for the failure is wrong platform vs any other root cause.

For 2 you have a problem since the resolve may be complex and encompass many transitive dependencies. As such, PEX would need to re-run the resolve with an additional constraint added of `that_dep != X.Y.Z`. That loop could happen many times resulting in effectively infinite resolve times.

So, AFAICT PEX has no way to do what you want generally. It would have to have a `--trust-me` option such that errors in steps 2 or 3 it would then have to say ... I'm not sure what.

Putting on the "I now am a Pex maintener" hat, do you have any ideas here that work well for when the `--trust-me` assertion is wrong? Anecdotally over ~9 years of the feature existing It seems it very often is and (more subjectively here) this is very often due to a user wanting the cool feature (build a Linux PEX on a Mac or vice versa) and not realizing you can't do that without cross-build support.

**Comment by jsirois** [comment] 2022-02-19 09:41
Just checking to make sure you know about `--resolve-local-platforms`. If you happen to be on a machine that matches the `--platform` when building the PEX, things will work regardless of sdists being present in the resolve. This isn't always useful but sometimes can be.

**Comment by matejsp** [comment] 2022-02-19 13:49
Where does pex get the whl from, if the wheel is not published on pip?
For example for pyqrcode what I get if I unpack the pex: folder with PyQRCode-1.2.1-py3-none-any.whl
So somebody generates the wheel in the end I presume.

Regarding getting lucky and noticing the resulting wheel tag as py2.py3-none-any is really the point here.
If project is native there is a high chance that it DOES have at least couple of prebuilt wheels. And if there are zero wheels published ... it is very likely just a pure python dependency.

Alternative would be for me to provide cache with locally prebuild wheels (just for the missing whls packages).
Or even better a configuration for skipping platform flag for some dependencies (like a list)

**Comment by jsirois** [comment] 2022-02-19 14:37
> Where does pex get the whl from, if the wheel is not published on pip?

Pex uses Pip to resolve and build distributions. The process is:
1. `pip download` (pass `--only-binary :all:` plus platform flags for a platform build).
2. For any non-wheels downloaded in 1, call `pip wheel --no-deps` on each in parallel to build wheels.
3. `pip install --no-deps` on each wheel from steps 1 and 2 in parallel to install the wheel in its own directory.
4. Package up a PEX from the installed wheels in step 3.

So Pex gets the wheel from step 2. 

Note that in step 1 we're forced to pass `--only-binary :all:` for a platform. See the 2nd paragraph of the Overview here: https://pip.pypa.io/en/stable/cli/pip_download/#overview

**Comment by jsirois** [comment] 2022-02-19 15:29
@matejsp stepping back a bit, `--platform` is really meant for dealing with creating platfrom-specific PEXes; generally mutliplatform ones. Most folks use this to create a PEX that can be run on either Mac or Linux and yet still have platform-specific requirements. The case you describe is not platform specific; so you can build a non-platform specific multiplatform PEX with just the `pex pyqrcode==1.2.1` you led with. Now you probably also want to specify shebang (`--python-shebang '/usr/bin/env python` for a truly universal PEX) and even `--interpreter-constraint` if the wheels will be py3 specific but otherwise universal (`py3-none-any` (`--interpreter-constraint '>=3').

**Comment by matejsp** [comment] 2022-02-19 19:17
What I wanted to achieve was multiplatform PEX. I was just trying to reproduce this open issue with the simplest use case. We have more than 180 dependencies that we have frozen in our virtualenv. pyqrcode, pypng, are just a couple of problematic ones. Then we also have a lot of platform specific ones like pyyaml, cryptography, cffi. Now those are candidates for platform specific part.

**Comment by jsirois** [comment] 2022-02-19 20:26
@matejsp OK. I think then I'd like to close this issue as answered assuming you can proceed with creating a wheel-house that fills in the gaps with pre-built wheels for the platforms you need and pointing Pex at it via `--index` or `--find-links`. Please speak up if you feel closing that way is premature, but I really don't see any way to do what you wanted.

**Closed by jsirois** 2022-02-19 20:26 UTC
Labels: answered, resolver
