### ISSUE TITLE
Support --constraints

### ISSUE THREAD

**Issue by Julian** [pantsbuild/pex#315] opened 2016-11-10 15:33 UTC
`pex` barfs on `pip` `--constraint`s.

```
pex runtests: commands[0] | /Users/Julian/Development/Thing/.tox/pex/bin/pex --no-wheel --requirement /Users/Julian/Development/Thing/requirements.txt /Users/Julian/Development/Thing[server] --entry-point twisted:twist --output-file /Users/Julian/Development/Thing/dist/thing
```

```
Traceback (most recent call last):
  File "/Users/Julian/Development/Thing/.tox/pex/bin/pex", line 11, in <module>
    sys.exit(main())
  File "/Users/Julian/Development/Thing/.tox/pex/site-packages/pex/bin/pex.py", line 540, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/Users/Julian/Development/Thing/.tox/pex/site-packages/pex/bin/pex.py", line 478, in build_pex
    resolvables.extend(requirements_from_file(requirements_txt, resolver_option_builder))
  File "/Users/Julian/Development/Thing/.tox/pex/site-packages/pex/requirements.py", line 94, in requirements_from_file
    return requirements_from_lines(fp.readlines(), builder=builder, relpath=relpath)
  File "/Users/Julian/Development/Thing/.tox/pex/site-packages/pex/requirements.py", line 78, in requirements_from_lines
    raise UnsupportedLine('Could not resolve line: %s (%s)' % (resolvable, e))
UnsupportedLine: Could not resolve line: --constraint https://example/constraints.txt (Unknown requirement type: --constraint https://example.com/constraints.txt)
```

**Comment by bloomonkey** [comment] 2017-04-05 15:49
This does seem to have been looked at in a recent PR (#335), but I believe that it is not yet correctly implemented.

`--constraints` in pip constrains the versions of libraries if, and only if, they are required by the package or one of its dependencies. An example would probably help here; given a file:

    # constraints.txt
    requests==2.0.0
    dontyouwantmebaby==0.0.0

pip will find and install (or just download in this example) only requests==2.0.0:

    $ pip download --constraint constraints.txt requests
    Collecting requests==2.0.0 (from -c constraints.txt (line 1))
      File was already downloaded /Users/john.harrison/code/pex/requests-2.0.0-py2.py3-none-any.whl
    Successfully downloaded requests

whereas pex attempts to satisfy a non-requirement:

    $ ./dist/pex27 --constraints constraints.txt requests
    Could not satisfy all requirements for dontyouwantmebaby==0.0.0:
        dontyouwantmebaby==0.0.0

**Comment by kwlzn** [comment] 2017-04-07 05:19
@bloomonkey thanks for the report. you're right this isn't working as intended - marking this as bug.

**Comment by bloomonkey** [comment] 2017-04-07 09:59
Thanks. I'll make a PR if I can figure out how to make it work correctly within the dependency resolution stuffs. In case it helps anyone else, my workaround for the time being is:

    mkdir deps
    pip download -d ./deps -r requirements.txt -c constraints.txt
    pex --no-pypi -f ./deps -r requirements.txt {args}

**Comment by kwlzn** [comment] 2017-04-07 17:53
cc @toumorokoshi based on his work in #335 

it's unclear if this is a regression or a longer-standing bug.

**Closed** 2019-11-14 22:46 UTC
Labels: bug, in progress, resolver
