### ISSUE TITLE
pex does not respect absense of `--resolve-local-platforms` on Mac M1, builds using local platform anyway

### ISSUE THREAD

**Issue by shalabhc** [pantsbuild/pex#2051] opened 2023-02-10 02:09 UTC
On an M1 Mac, when I don't specify `--resolve-local-platforms`, `pex` will still build dependencies using the local interpreter matching the `--python` flag, even when binary wheels exist. 
When using rosetta Python (x86 emulation), this issue does not exist.

Reproduction - I have two venvs, one for m1 native (arm) and one for rosetta (x86)):
Note the binary wheel exists for `grpcio` for requested `--platform`. Using `--complete-platform` does not help.

```
# x86 works as expected - pulls the binary wheel and makes the pex
% pex --platform=manylinux2014_x86_64-cp-38-cp38 --python=python3.8 --pip-version=22.2.2 --resolver-version=pip-legacy-resolver grpcio==1.47.2 -o grpcio.pex   
(x86-python) ~/src/issues/pex-python-flag
% unzip -l grpcio.pex | grep 'whl/$'                                                                                                                        
        0  01-01-1980 00:00   .deps/grpcio-1.47.2-cp38-cp38-macosx_10_10_x86_64.whl/
        0  01-01-1980 00:00   .deps/grpcio-1.47.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/
        0  01-01-1980 00:00   .deps/six-1.16.0-py2.py3-none-any.whl/
```

```
# same command in arm just starts building a wheel
 pex --platform=manylinux2014_x86_64-cp-38-cp38 --python=python3.8 --pip-version=22.2.2 --resolver-version=pip-legacy-resolver grpcio==1.47.2 -o grpcio.pex -v
pex: Building pex :: Resolving distributions (grpcio==1.47.2) :: Resolving requirements. :: Resolving for:
  /Users/shalabh/src/issues/pex-python-flag/arm-python/bin/python3.8
pex: Hashing pex                                                                                                                                                   pex: Hashing pex: 90.3ms                     
pex: Isolating pex: 0.1ms
pex: Building pex :: Resolving distributions (grpcio==1.47.2) :: Resolving requirements. :: Building distributions for:
  BuildRequest(target=LocalInterpreter(id='Users.shalabh.src.issues.pex-python-flag.arm-python.bin.python3.8', platform=Platform(platform='macosx_12_0_arm64', impl='cp', version='3.8.16', version_info=(3, 8, 16), abi='cp38'), marker_environment=MarkerEnvironment(implementation_name='cpython', implementation_version='3.8.16', os_name='posix', platform_machine='arm64', platform_python_implementation='CPython', platform_release='21.6.0', platform_system='Darwin', platform_version='Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101', python_full_version='3.8.16', python_version='3.8', sys_platform='darwin'), interpreter=PythonInterpreter('/Users/shalabh/src/issues/pex-python-flag/arm-python/bin/python3.8', PythonIdentity('/Users/shalabh/src/issues/pex-python-flag/arm-python/bin/python3.8', 'cp38', 'cp38', 'macosx_12_0_arm64', (3, 8, 16)))), source_path='/Users/shalabh/.pex/downloads/resolver_download.gmefuolk/Users.spex: Building /Users/shalabh/.pex/downloads/resolver_download.gmefuolk/Users.shalabh.src.issues.pex-python-flag.arm-python.bin.python3.8/grpcio-1.47.2.tar.gz to /Users/shalabh/.pex/built_wheels/sdists/grpcio-1.47.2.tar.gz/c7f888b067f2b1833a5670f20eeac2c6063039a23a99b799929de065c1b18692/cp38-cp38-macosx_12_0_arm64

<CTRL-C>
```

This has something to do with the `--python` flag because if I remove that, even arm quickly builds the pex from the pypi wheel.

**Comment by jsirois** [comment] 2023-02-10 02:16
@shalabhc this is by design but obviously not what you expect. Each --python, --interpreter-constraint, --platform and --complete-platform adds to a list of targets resolved for; i.e. they each add a "platform" to a multi-platform PEX.

**Comment by jsirois** [comment] 2023-02-10 02:16
The question then is what you are trying to do by adding --python?

**Comment by jsirois** [comment] 2023-02-10 02:27
More spin: `--resolve-local-platforms` is a modifier for `--platform` and --complete-platform` and that is all. It has no bearing on either `--python` or `--interpreter-constraint` which select 1 and 1+ local interpreters unconditionally. After all that selection you are left with 1 or more real local interpreters and 1 or more foreign platforms. For each real local interpreter if there is no wheel, that interpreter will be used to build an sdist into a wheel for that real local interpreter.

Does that make sense?

**Comment by shalabhc** [comment] 2023-02-10 03:49
Ah I did not realize this. I assumed `--python=python3.8` selected the interpreter on the target (it's under "PEX target environment options:"). Specifically I thought it meant "when this pex is run, ensure it is run with a binary called `python3.8` and fail if `python3.8` is not present in the target environment". I did not think it affected how the build itself was done.

I can exclude `--python=python3.8` but how do I tell it run the pex with `python3.8` in case the target has multiple interpreters present?

Here I think it makes sense because `grpcio` has a wheel for x86 but no wheel for arm. The only confusion that remains is: what is the point of building the wheel for arm when it is not going to be used? IIUC it will build the arm wheel but then discard it because the `--platform` specifies that only the manylinux wheel should be included in the pex.

**Comment by jsirois** [comment] 2023-02-10 03:51
The point is Pex thinks you're asking it to build a multiplatform PEX file that works on Linux x86_64 and Mac arm.

**Comment by jsirois** [comment] 2023-02-10 03:54
To require the PEX runs using python3.8 you need not do anything. Pex gained the ability to probe compatibility on boot a while back. That can take time though, so you can steer by setting the --python-shebang option. More direct, if you control the PEX execution command, change it from `my.pex ...` to `/this/exact/python my.pex ...`.

**Comment by shalabhc** [comment] 2023-02-10 05:02
Indeed I just noticed it is a fat pex on macos x86 (two wheels for grpcio):
```
 unzip -l grpcio.pex | grep 'whl/$'
        0  01-01-1980 00:00   .deps/grpcio-1.47.2-cp38-cp38-macosx_10_10_x86_64.whl/
        0  01-01-1980 00:00   .deps/grpcio-1.47.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/
```

I knew about multi platform pexes and created them intentionally with multiple `--platform` flags, but did not realize `--python` was also adding the local platform.

Thanks for the explanation!

**Comment by jsirois** [comment] 2023-02-10 05:09
You're welcome. I'll close this as answered, but please re-open if you have more questions.

**Closed** 2023-02-10 05:09 UTC
Labels: question, answered
