### ISSUE TITLE
vendored pip prompts for user input

### ISSUE THREAD

**Issue by asherf** [pantsbuild/pex#983] opened 2020-06-02 21:58 UTC
This obviously breaks pants.
It has to do with files in the temp directory, seeing this mostly on an ubuntu box.

since we vendor pip, we should probably modify this code to avoid the user interaction.
```
ProcessExecutionFailure:                 Process 'Resolving 28 requirements: <REDACTED>' failed with exit code 1.
                stdout:
                The file /tmp/tmp_vbdtx6s/cp38-cp38/rsa-4.0-py2.py3-none-any.whl exists. (i)gnore, (w)ipe, (b)ackup, (a)abort

                stderr:
                ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/cli/base_command.py", line 172, in _main
    status = self.run(options, args)
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/commands/download.py", line 146, in run
    resolver.resolve(requirement_set)
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/legacy_resolve.py", line 185, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/legacy_resolve.py", line 341, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/legacy_resolve.py", line 290, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    local_path = unpack_url(
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/operations/prepare.py", line 308, in unpack_url
    return unpack_http_url(
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/operations/prepare.py", line 172, in unpack_http_url
    _copy_file(from_path, download_dir, link)
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/operations/prepare.py", line 113, in _copy_file
    response = ask_path_exists(
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/utils/misc.py", line 224, in ask_path_exists
    return ask(message, options)
  File "/tmp/process-execution2mCsRC/pex_root/pip.pex/240b20f98d345b70b316f7e734d4cea20bde73b6/.deps/pip/pip/_internal/utils/misc.py", line 242, in ask
    response = input(message)
EOFError: EOF when reading a line
pid: 24972 -> /usr/bin/python3.8 /tmp/process-execution2mCsRC/pex_root/pip.pex/2
```

@stuhood @benjyw  @jsirois

**Comment by benjyw** [comment] 2020-06-02 21:59
Good find. There may be a pip flag that overrides this. If not, we should modify it in our vendored version.

**Comment by asherf** [comment] 2020-06-02 22:04
It seems somehow related to pantsd, since if I disable it, I stop getting this error.
FWIW, I was trying to build a bunch of binaries in a single run.
i.e. ./pants binary src/python/toolchain/<some_dir>/::
where under <some_dir> I have a bunch of directories (different nesting levels) with a bunch of build files and a bunch of binary targets defined in them.
@stuhood

**Comment by asherf** [comment] 2020-07-06 13:04
this still happens. @jsirois  @stuhood @benjyw 
https://travis-ci.com/github/pantsbuild/pants/jobs/357763904#L686

<img width="1231" alt="Screen Shot 2020-07-06 at 6 04 29 AM" src="https://user-images.githubusercontent.com/1268088/86596108-8fd9ee80-bf4e-11ea-9b90-22ce9321472a.png">

@jsirois @benjyw @stuhood @Eric-Arellano

**Comment by jsirois** [comment] 2020-07-06 15:06
This is easy enough to fix. I'll spend a bit of time though trying to figure out how pip can get in this situation, work directories pex gives to pip should be unique but this may be a straight up concurrency issue in pip too.

**Comment by jsirois** [comment] 2020-07-06 15:24
> There may be a pip flag that overrides this. If not, we should modify it in our vendored version.

There is. Older versions of 2.x set the flag:
```
$ PYTHONPATH=pex/vendor/_vendored/pip python -mpip download --help
...
--exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
```

**Comment by jsirois** [comment] 2020-07-06 15:43
@asherf it appears this can happen whenever the pex command involves multiple target pythons with degenerate major.minor.buildflags. In other words, if you have two or more different CPython 3.8 distributions installed and discoverable by Pex in the case of the original backtrace you provided. I'm working on fixing this underlying issue but confirmation that you might have seen these errors on a system with multiple Python distributions degenerate in this way would be helpful confirmation of this diagnosis.

**Comment by asherf** [comment] 2020-07-06 15:59
I haven't seen that happen locally (on mac os) in a while.
The recent occurrence was in CI, when https://github.com/pantsbuild/pants/pull/10259 was merged (which triggered a resolve)
I am not sure about the travis setup in terms of python interpreters but I would assume that env has less python interpreters available than a regular dev machine

**Comment by jsirois** [comment] 2020-07-06 16:35
Thanks Asher.

Confirmed that the screen-shot case above in Pants CI sees 2 python 2.7s via https://github.com/pantsbuild/pants/pull/10265

In particular there are 3 unique python 2.7 interpreters seen by the Integration CI shard:
```
$ pyenv versions --bare | xargs pyenv prefix
/opt/pyenv/versions/2.7.15:/opt/pyenv/versions/3.6.7:/opt/pyenv/versions/3.7:/opt/pyenv/versions/3.7.1
The command "pyenv versions --bare | xargs pyenv prefix" exited with 0.
$ which -a python2.7
/home/travis/virtualenv/python2.7.15/bin/python2.7
/opt/pyenv/shims/python2.7
/opt/pyenv/shims/python2.7
/usr/bin/python2.7
The command "which -a python2.7" exited with 0.
```

**Comment by jsirois** [comment] 2020-07-06 16:47
OK both download and build have this problem of operating over degenrate target interpreters. In the download case, this can lead to the issue described here. In the build case, there are no concurrency issues since Pex uses AtomicDirectory, but we do waste parallel builds against degenerate interpreters that will all produce the same wheel. So I think centrally fixing Pex use of local distribution targets to dedup by target interpreter abi is the right way to go here to both fix this bug and improve performance when sdists or local projects are involved in the resolve.

**Comment by jsirois** [comment] 2020-07-07 15:34
Although deduping abi degeneracy makes sense for building wheels from sdists, it does not make strict sense for downloads. In a download, a distribution can drill down on the patch version of the python interpreter when selecting compatibility for example: https://www.python.org/dev/peps/pep-0345/#requires-python. Other attributes of the target interpreter finer grained than the abi can also be in play since environment markers can be present even in Requires-Python: https://www.python.org/dev/peps/pep-0345/#environment-markers. As such, resolving using Python 2.7.6 could in fact produce different results from resolving using 2.7.18. Once downloaded though, a wheel produced with 2.7.6 should be functionally identical to one produced by 2.7.18. The wheel names will be identical at any rate making this operationally true at the least. This implies that the actual instances of downloads (resolves) being different should be rare or non-existant, but the extra degrees of freedom are there in the spec unfortunately. Implementing download deduping by abi will require some form of escape hatch, say `--resolve-degenerate-interpreters` with a lengthy option help explaining what this means. Even with that, diagnosing that this option is needed will be nearly impossible.

As such, for now I'll focus on just fixing by using a download destination path uniquely coupled to the interpreter in play instead of to just its abi. I'll break out the download and build abi degeneracy fixing steps as optimizations to be addressed seperately in two new issues.

**Comment by stuhood** [comment] 2020-07-07 17:16
In the pantsbuild/pants case, could we be doing more to limit the number of interpreters that are used for "internal" pexes... those that will only be used in tests rather than exiting the process via `./pants binary`, for example?

I could imagine selecting exactly one interpreter in more cases, although it might make things challenging in mixed local/remote situations.

**Comment by jsirois** [comment] 2020-07-07 17:32
> In the pantsbuild/pants case, could we be doing more to limit the number of interpreters that are used for "internal" pexes... those that will only be used in tests rather than exiting the process via ./pants binary, for example?

Yes. My old branch over in pants that uses the relatively new download + install APIs instead of resolve does exactly that:
https://github.com/jsirois/pants/blob/17abd06032b33cec54fba255cf23a652b10223aa/src/python/pants/backend/python/rules/pex_tools/resolver.py#L42
https://github.com/jsirois/pants/blob/17abd06032b33cec54fba255cf23a652b10223aa/src/python/pants/backend/python/rules/resolve.py#L148-L149

**Closed** 2020-07-10 17:48 UTC
Labels: bug, in progress, resolver
