### ISSUE TITLE
Documentation on readthedocs is broken

### ISSUE THREAD

**Issue by tomecki** [pantsbuild/pex#2265] opened 2023-10-12 09:46 UTC
The documentation linked from the main README.md is broken.

https://pex.readthedocs.io/ redirects to https://pex.readthedocs.io/en/v2.1.148/, this in turn displays:
```
404 Not Found
You are browsing the documentation of pex. The documentation page you are looking for was not found.
```
![Screenshot 2023-10-12 at 11 45 03](https://github.com/pantsbuild/pex/assets/632556/b5deea4a-d4a1-46c4-9803-38ba9b310140)

**Comment by benjyw** [comment] 2023-10-12 21:49
Thanks for the report! Until we fix you can go directly to https://pex.readthedocs.io/en/v2.1.147/ to see the docs for the previous version.

**Comment by benjyw** [comment] 2023-10-12 22:49
This is due to this RTD build error: https://github.com/sphinx-doc/sphinx/issues/10291, which is caused by latest Sphinx not working with Jinja2==3.1.0. 

This is happening now because of https://blog.readthedocs.com/defaulting-latest-build-tools/. Prior to that change, RTD happened to pin Jinja2<3.1.0. Post that change, they don't.

**Comment by benjyw** [comment] 2023-10-12 22:59
Fixed in https://github.com/pantsbuild/pex/pull/2266

**Closed** 2023-10-13 07:38 UTC

**Comment by tomecki** [comment] 2023-10-13 10:09
Thanks a lot!
