### ISSUE TITLE
invalied specifier *

### ISSUE THREAD

**Issue by hollandmdwx** [pantsbuild/pex#2269] opened 2023-10-25 10:19 UTC
Hello, I fail to build a pex file because of the error "Invalid specifier: '>=3.6.*'" that refers to a dependency. Is there any way to work around this?

**Comment by jsirois** [comment] 2023-10-25 10:27
Can you provide more details? The more the better; preferably the full Pex command line including the contents of any files use (if you use something like `-r requirements.txt` in the command line).

**Comment by hollandmdwx** [comment] 2023-10-25 13:29
of course! So I was using this command: pex -r requirements.txt -c uvicorn -o service.pex

I created my project with poetry and the only file I could find with '>=3.6.*' in it was the poetry.lock file with following line: 

[[package]]
name = "boilerpy3"
version = "1.0.6"
description = "Python port of Boilerpipe, for HTML boilerplate removal and text extraction"
optional = false
python-versions = ">=3.6.*"
files = [
    {file = "boilerpy3-1.0.6-py3-none-any.whl", hash = "sha256:0203dde43291cad959d4f47663bc47c34344c1377f4914a8291841e8721234a5"},
    {file = "boilerpy3-1.0.6.tar.gz", hash = "sha256:c864c0041c3197ad8c118109b252c2c564133614e93068bf226eaf6d217304bb"},
]

this are my requirements: 

accelerate==0.23.0
anyio==4.0.0
appdirs==1.4.4
attrs==23.1.0
Authlib==1.2.1
backoff==2.2.1
boilerpy3==1.0.6
build==0.10.0
CacheControl==0.12.14
cattrs==23.1.2
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.0
cleo==2.0.1
click==8.1.7
cmake==3.27.7
colorama==0.4.6
crashtest==0.4.1
cryptography==41.0.4
distlib==0.3.7
docopt==0.6.2
dulwich==0.21.6
Events==0.5
farm-haystack==1.21.2
fastapi==0.100.0
filelock==3.12.4
fsspec==2023.9.2
grpcio==1.59.0
grpcio-tools==1.59.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
html5lib==1.1
httpcore==0.18.0
httpx==0.25.0
huggingface-hub==0.18.0
hyperframe==6.0.1
idna==3.4
importlib-metadata==6.8.0
inflect==7.0.0
iniconfig==2.0.0
installer==0.7.0
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.1.2
joblib==1.3.2
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
keyring==23.13.1
langdetect==1.0.9
lazy-imports==0.3.1
lit==17.0.3
lockfile==0.12.2
MarkupSafe==2.1.3
monotonic==1.6
more-itertools==10.1.0
mpmath==1.3.0
msgpack==1.0.7
networkx==3.2
nltk==3.8.1
num2words==0.5.13
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.2
pandas==2.1.1
pexpect==4.8.0
Pillow==10.1.0
pkginfo==1.9.6
platformdirs==3.11.0
pluggy==1.3.0
poetry==1.5.1
poetry-core==1.6.1
poetry-dotenv-plugin==0.2.0
poetry-plugin-export==1.5.0
portalocker==2.8.2
posthog==3.0.2
prompthub-py==4.0.0
protobuf==4.24.4
psutil==5.9.6
ptyprocess==0.7.0
pycparser==2.21
pydantic==1.10.13
pyproject_hooks==1.0.0
pytest==7.4.2
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3.post1
PyYAML==6.0.1
qdrant-client==1.6.3
qdrant-haystack==1.0.11
quantulum3==0.9.0
rank-bm25==0.2.2
rapidfuzz==2.15.2
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
requests-cache==0.9.8
requests-toolbelt==1.0.0
rpds-py==0.10.6
safetensors==0.4.0
scikit-learn==1.3.1
scipy==1.9.3
SecretStorage==3.3.3
sentence-transformers==2.2.2
sentencepiece==0.1.99
shellingham==1.5.3
six==1.16.0
sniffio==1.3.0
sseclient-py==1.8.0
starlette==0.27.0
sympy==1.12
taskipy==1.12.0
tenacity==8.2.3
threadpoolctl==3.2.0
tiktoken==0.5.1
tokenizers==0.13.3
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.0
torchvision==0.15.1
tqdm==4.66.1
transformers==4.32.1
triton==2.0.0
trove-classifiers==2023.10.18
typing_extensions==4.8.0
tzdata==2023.3
url-normalize==1.4.3
urllib3==1.26.18
uvicorn==0.23.2
validators==0.22.0
virtualenv==20.24.5
weaviate-client==3.24.2
webencodings==0.5.1
zipp==3.17.0

**Comment by jsirois** [comment] 2023-10-26 07:15
@hollandmdwx the issue is that the published wheel for boilerpy3 is bogus. Observe:
```
$ unzip -qc boilerpy3-1.0.6-py3-none-any.whl boilerpy3-1.0.6.dist-info/METADATA | grep Requires
Requires-Python: >=3.6.*
```

If you read the PEP-440 spec, you'll see `*` is only for equality; not for ordered comparisons (<, <=, >, >=): https://peps.python.org/pep-0440/#version-matching

What boilerpy3 means to say is simply `>=3.6`.

I noticed in your Poetry lock you have special local file versions for boilerpy3, is that a workaround of some sort?

**Comment by jsirois** [comment] 2023-10-27 07:24
Ah, those aren't local files, that's just the Poetry lock syntax.

**Comment by hollandmdwx** [comment] 2023-10-27 09:04
Exactly, it is only a matter of the lock file. Unfortunately, I can't change the dependency wording >=3.6.* because the library was installed via another dependency. Should I reach out to boilerpy3, or is there another way to fix the problem?

**Comment by jsirois** [comment] 2023-10-28 06:15
Of course you should always reach out. In this case you can get two for one by forking, fixing, sending that fix off in a PR, and consuming the fix with an explicit VCS requirement (`boilerpy3 @ git+https://github.com/...@<this sha>`). It's true that you don't directly depend on boilerpy3; so adding a direct dep as a workaround is not awesome, but it buys the owners time to accept your patch.

**Comment by jsirois** [comment] 2023-11-01 20:45
Expanding on the suggestion above: https://github.com/jmriebold/BoilerPy3/pull/10
And using that looks like so in `requirements.txt`:
```diff
diff -u requirements.txt.orig requirements.txt
--- requirements.txt.orig       2023-11-01 13:26:10.967405214 -0700
+++ requirements.txt    2023-11-01 13:26:32.147399804 -0700
@@ -4,7 +4,10 @@
 attrs==23.1.0
 Authlib==1.2.1
 backoff==2.2.1
-boilerpy3==1.0.6
+
+#boilerpy3==1.0.6
+boilerpy3 @ git+https://github.com/jsirois/BoilerPy3@5a99a35aa925ac4fee50be5c08d251fd028df905
+
 build==0.10.0
 CacheControl==0.12.14
 cattrs==23.1.2
```

And that results in:
```
$ pex --python python3.11 -r requirements.txt -c uvicorn -o service.pex
/home/jsirois/bin/pex.venv/lib/python3.12/site-packages/pex/pex_builder.py:114: PEXWarning: The PEX zip at service.pex~ is not a valid zipapp: Could not find the `__main__` module.
This is likely due to the zip requiring ZIP64 extensions due to size or the
number of file entries or both. You can work around this limitation in Python's
`zipimport` module by re-building the PEX with `--layout packed` or
`--layout loose`.
  pex_warnings.warn(message)
$ zipinfo service.pex | tail -1
30652 files, 4840690000 bytes uncompressed, 2451330683 bytes compressed:  49.4%
```

So the PEX is too big a zip file (>32 bits (~4GB) size uncompressed). That is fixed by using the suggestion in the warning:
```
$ pex --python python3.11 -r requirements.txt -c uvicorn -o service.pex --layout packed
$ ./service.pex/__main__.py --version
Running uvicorn 0.23.2 with CPython 3.11.6 on Linux
```

**Comment by jsirois** [comment] 2023-11-01 20:46
@hollandmdwx I'm going to close this issue as an answered question, but please speak up if you find anything unresolved still.

**Closed by jsirois** 2023-11-01 20:46 UTC
Labels: question, in progress
