### ISSUE TITLE
Release 2.1.75 tag not signed

### ISSUE THREAD

**Issue by lmartinez-mirror** [pantsbuild/pex#1701] opened 2022-03-31 20:25 UTC
Hi, I package pex for the AUR on Arch Linux. Arch packaging guidelines state that if upstream provides signed sources, I need to verify using the GPG key. Additionally, I cannot remove GPG verification if upstream stops signing sources.

Release tag 2.1.75 isn't signed; please sign it, preferably without the GitHub web-signing key. I'd greatly appreciate it!

**Comment by jsirois** [comment] 2022-04-01 20:28
@lmartinez-mirror I had not hardened the release process; so this snuck through. At worst I'll get a fix out ~8am US Pacific time tomorrow.

**Comment by jsirois** [comment] 2022-04-02 14:45
Actually, the tag is signed:
```
$ git show v2.1.75 -q
tag v2.1.75
Tagger: Eric Arellano <ericarellano@me.com>
Date:   Thu Mar 31 11:07:43 2022 -0700

Release 2.1.75
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEwJS9cBp16BL1lkgbdRi6HnNO8/oFAmJF7e8ACgkQdRi6HnNO
8/ptMQ//QySIuD9TUCsONCGkxtfBAdSqU4xwevVA4PgNhcLZBywHCxRuiOESuUsU
tmBap+Fees6HZ6wrRRWaRbBi6oBmYwP/iyA/cA9wIN63yG78c2HctgV2prlCBIu/
qcwZkVBn2fb5Bt4nzzbc3cB2DnF0kELaDFHVTMRgLxLfJtxbu4Z2ecJuIFZbNSb/
qzhqNDE7Tom69nyRNwzgo47Q03SvBF//jhw1JiFqtP2rfC2zGbIXrquGFXLbf09y
+atSIjBP/0I0KRaHVocRl6NMBkOWPsIxSllaASALW9SQxVdXHD31g0Uc0QjNdpXZ
aWVfwEh60RnEtCW9m+lpCtTTZ5c0oNOPKDWaSm9VMCI9mXsNVdQLsCfI5x4OK2LT
7n7oMapVqGAyuZt/l2NDFedM3Dq1428NYaVzfKZih/AbzmF/DV93nnzRTczeR/Zs
m0c5CVaMjuGIj91gDY7E5zCh2D9+edf6iUjV3p9vWRz4DFc+MrDpo7DKPMIIqx9r
9PEiGfMgXoOXupvK/xxS8zpLwU0wQAX8xWmuvPSnhpjyINGo5phB3/zukpzyWXtJ
BS3jFUlKrEfINlAMkm9/lilLS28udiQ5fSiyFGtmtRYX5RknaLCRmtNW/GYbL4y9
a5h7+JTjFY1zXGQM8/x56lVXtl1arCjSeeZgZEYQHbgEMLnzHHA=
=aHfW
-----END PGP SIGNATURE-----

commit ddc4ca107479ed9d12fe67defd01643f6c388b73 (tag: v2.1.75)
Author: Eric Arellano <14852634+Eric-Arellano@users.noreply.github.com>
Date:   Thu Mar 31 11:02:37 2022 -0700

    Prepare 2.1.75 (#1699)
    
    Closes #1691.
```

@Eric-Arellano I think you just need to update your GitHub account settings to include your PGP key.

Looks like so:
![image](https://user-images.githubusercontent.com/157586/161388445-adf2e8c9-60a4-4498-b432-b5fcd76e4737.png)

After that, I think the tag will pick up an icon like this:
![image](https://user-images.githubusercontent.com/157586/161388495-73a6b800-72c6-435c-bbbd-07821a23a92b.png)

**Comment by jsirois** [comment] 2022-04-02 14:49
@lmartinez-mirror in the meantime, I've added a tag `v2.1.75-public-signed`: https://github.com/pantsbuild/pex/releases/tag/v2.1.75-public-signed

Perhaps you can modify your PKGBUILD for this release and use that tag?

**Comment by Eric-Arellano** [comment] 2022-04-02 16:49
hm idk what im doing wrong. i confirmed the key in github == what i use locally. i did not have on vigilant mode before but turned that on

<img width="642" alt="Captura de Pantalla 2022-04-02 a la(s) 9 47 15 a  m" src="https://user-images.githubusercontent.com/14852634/161392963-b620d4d5-db05-4bbb-a66e-a0c8c571fd27.png">

<img width="805" alt="Captura de Pantalla 2022-04-02 a la(s) 9 47 49 a  m" src="https://user-images.githubusercontent.com/14852634/161392975-4380157d-4625-4ba2-b339-6b2af670d2a4.png">

**Comment by jsirois** [comment] 2022-04-02 17:17
@Eric-Arellano perhaps publish that key. It looks like you have only another published: https://pgp.mit.edu/pks/lookup?search=Eric+Arellano&op=index

**Comment by jsirois** [comment] 2022-04-04 18:07
@lmartinez-mirror you could also just skip 2.1.75 and move to 2.1.76 which was just released: https://github.com/pantsbuild/pex/releases/tag/v2.1.76

**Comment by jsirois** [comment] 2022-04-04 18:09
@Eric-Arellano I've handed this off to you to close out once you get your current in-use signing key published. All the other angles are now covered fwict.

**Comment by Eric-Arellano** [comment] 2022-04-04 21:57
Huzzah!
<img width="419" alt="Captura de Pantalla 2022-04-04 a la(s) 2 56 26 p  m" src="https://user-images.githubusercontent.com/14852634/161638849-ab125376-e9f5-42a4-bc40-e25f7600b3c2.png">

The issue is that my GitHub key only had one email address associated with it, and apparently I used a different email when I did the release. I changed my key to use the new email as well, re-uploaded to github, and now it works. Thank you John for the help, and thank you @lmartinez-mirror for the report!

**Comment by jsirois** [comment] 2022-04-04 22:12
@Eric-Arellano I don't think that will cut it. The GitHub icons are a guidepost - but GitHub is a walled garden. @lmartinez-mirror maintains an Arch Linux package that gets built as part of the Arch packaging system. It cares not a bit about GitHub or GitLab or even, necessarily git. It still wants to verify the tag though.

On a machine starting with no pgp setup:
```
jsirois@siroisdesign:~/pex$ git verify-tag v2.1.76
gpg: Signature made Mon Apr  4 17:18:39 2022 UTC
gpg:                using RSA key A1FE765B15233EAD18FA6ABB93E55CB567B5C626
gpg: Can't check signature: No public key
jsirois@siroisdesign:~/pex$ git verify-tag v2.1.75
gpg: Signature made Thu Mar 31 18:07:43 2022 UTC
gpg:                using RSA key C094BD701A75E812F596481B7518BA1E734EF3FA
gpg: Can't check signature: No public key
```

Ok, grab the keys:
```
jsirois@siroisdesign:~/pex$ gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 93E55CB567B5C626
gpg: /home/jsirois/.gnupg/trustdb.gpg: trustdb created
gpg: key 93E55CB567B5C626: public key "John Sirois (CODE SIGNING KEY) <jsirois@apache.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
jsirois@siroisdesign:~/pex$ gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys C094BD701A75E812F596481B7518BA1E734EF3FA
gpg: keyserver receive failed: No data
```

That's bad and means @lmartinez-mirror still has a problem for `v2.1.75`.

IOW, I can now verify `v2.1.76` but still can't verify `v2.1.75`:
```
jsirois@siroisdesign:~/pex$ git verify-tag v2.1.76
gpg: Signature made Mon Apr  4 17:18:39 2022 UTC
gpg:                using RSA key A1FE765B15233EAD18FA6ABB93E55CB567B5C626
gpg: Good signature from "John Sirois (CODE SIGNING KEY) <jsirois@apache.org>" [unknown]
gpg:                 aka "John Sirois (https://people.apache.org/~jsirois/) <jsirois@apache.org>" [unknown]
gpg:                 aka "John Sirois <john.sirois@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: A1FE 765B 1523 3EAD 18FA  6ABB 93E5 5CB5 67B5 C626
jsirois@siroisdesign:~/pex$ git verify-tag v2.1.75
gpg: Signature made Thu Mar 31 18:07:43 2022 UTC
gpg:                using RSA key C094BD701A75E812F596481B7518BA1E734EF3FA
gpg: Can't check signature: No public key
```

I think you really will have to update your published key / publish this new one.

**Comment by jsirois** [comment] 2022-04-04 22:15
I'll also assign to myself in tandem to get docs added to `RELEASE.rst` about the need for all this. Pants probably should be doing the same, but, as far as I know, is not an application packaed by any OS. Pex has been so since back in late 2011 IIRC starting with Debian / Ubuntu.

**Comment by lmartinez-mirror** [comment] 2022-04-04 22:56
Thank you all for addressing this quickly! I'll go ahead and target release 2.1.76.

**Comment by Eric-Arellano** [comment] 2022-04-05 20:26
I've added myself to https://pgp.mit.edu/pks/lookup?search=eric-arellano&op=index.

```
pub  4096R/[734EF3FA](https://pgp.mit.edu/pks/lookup?op=get&search=0x7518BA1E734EF3FA) 2021-07-29 [Eric Arellano <ericarellano@me.com>](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x7518BA1E734EF3FA)
                               Eric Arellano <14852634+Eric-Arellano@users.noreply.github.com>
```

```
❯ git verify-tag v2.1.75
gpg: Firmado el Thu Mar 31 11:07:43 2022 MST
gpg:                usando RSA clave C094BD701A75E812F596481B7518BA1E734EF3FA
gpg: Firma correcta de "Eric Arellano <ericarellano@me.com>" [absoluta]
gpg:                 alias "Eric Arellano <14852634+Eric-Arellano@users.noreply.github.com>" [absoluta]
```

Thanks for the help! New world for me.

**Comment by Eric-Arellano** [comment] 2022-04-05 20:26
(reopening because we still need to fix our release docs so that this doesn't happen with future releases)

**Closed** 2022-04-06 16:42 UTC
Labels: bug, in progress, release, documentation
